name: Release package
<<<<<<< HEAD

=======
>>>>>>> origin/main
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    permissions:
      contents: write
    uses: ./.github/workflows/build.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/

      - name: Attach artifacts to github release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.whl
          prerelease: False
          body_path: CHANGELOG.md
